http:
  listen-address: 0.0.0.0:8080
  secret: music-match2022!
neo4j:
  endpoint: "neo4j+s://01f4c3bc.databases.neo4j.io"
  plaintext: false
  username: neo4j
  password: YuoQdM62FKAQDuzesY4S6GgukPcSAtQ4OPzyQsL1fWI
  retry:
    interval: 1000 #interval between each request in ms
    max:  5 #max number of retries before aborting
    timeout: 25000 #timeout ms
  pools:
    timeout: 5000
    max-pool-size: 100
    acq-timeout: 10000

  #username: "neo4j"
  #password: "KZ02v5sH02S4Ha5ZjviVfI9sfSlEQEMtXtkQCOMecfs"