http:
  listen-address: 0.0.0.0:8081
neo4j:
 # endpoint: "neo4j+s://bd75ff33.databases.neo4j.io"
  endpoint: "neo4j://127.0.0.1"
  plaintext: true
  #username: "neo4j"
  #password: "KZ02v5sH02S4Ha5ZjviVfI9sfSlEQEMtXtkQCOMecfs"