services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    environment:
      NEO4J_AUTH: "none"
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
  init:
    image: neo4j:latest
    depends_on:
      - neo4j
    container_name: neo4j-init
    volumes:
      - "./neo4j/config/init.cypher:/init.cypher"
    entrypoint: "bash -c 'while true; do if cypher-shell --address=neo4j://neo4j:7687 -f /init.cypher; then break; fi; done'"
  # music-match:
  #   image: music-match:latest
  #   depends_on:
  #     - neo4j
  #     - init
  #   ports:
  #     - "8080:8080"
