name: Docker
on:
  push:
    tags:
      - v*
    branches:
      - master
      - develop
      - release/v*.*.*
  pull_request:
    types:
      - synchronize
      - opened
    branches:
      - master
      - develop
      - release/v*.*.*
permissions:
  contents: read
  pull-requests: read
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: docker build -t music-match:test .
      - name: Cleanup
        run: docker rmi -f music-match:test